### ISSUE TITLE
update to new elastic release, build to latest nuget. build fails

### ISSUE THREAD

**Issue by papyr** [amitstefen/mongo_app#1]
Hi, can you please update this to latest redis, mongodb and asp please. and checkin a working build, would lke to try it out

**Comment by pro-dev-amit** [comment]
Let me see if I've time to do that, chances are bleak though. There may be cases of breaking changes with the newer APIs, the tech has moved forward a lot since I touched this code since some 3-4 yrs back. Now things are moving towards async operations for better throughput. All the APIs you see in this application are basically providing async methods as well at this moment. Try with those.

But whatever concepts are explained here, they're pretty easy to structure even with newer APIs.

Also, think about porting your application code to dotnet core, it is going to be the future and is advancing at much faster rate. Even in my job, we've just started to port things to .netcore2.2. It'll give us ease and flexibility of deployment to any platform(win or *nix). Sorry to disappoint you at the moment.
